### ISSUE TITLE
Unable to compile OMNeT++ 6.0

### ISSUE THREAD

**Issue by SpeedJack** [omnetpp/omnetpp#920]
I run:
```
source setenv
./configure
make
```
I can compile ometpp 5.7 successfully. But with omnetpp 6.0 I get the following error during `make`:
```
Building release and debug mode executables. Type 'make help' for further options.

***** Configuration: MODE=release, TOOLCHAIN_NAME=clang, SHARED_LIBS=yes, LIB_SUFFIX=.so ****
[.......]
===== Compiling sim ====
MSGC: sim_std.msg
/home/speedjack/repos/omnetpp-6.0/bin/opp_msgtool: symbol lookup error: /home/speedjack/repos/omnetpp-6.0/bin/opp_msgtool: undefined symbol: _ZN7omnetpp6nedxml11MsgCompiler19BUILTIN_DEFINITIONSE
make[2]: *** [Makefile:160: sim_std_m.cc] Error 127
make[1]: *** [Makefile:134: sim] Error 2
make: *** [Makefile:35: allmodes] Error 2
```
I'm unable to figure out what is missing.

Here the output of `./configure`:
```
configure: Environment variables (PATH and PYTHONPATH) are correctly set.
configure: Reading configure.user for your custom settings.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for clang... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for clang++... clang++
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking for clang++... clang++
checking for c++14 support... yes
checking for ranlib... ranlib
checking whether LLD linker is available... yes
checking whether clang++ supports -fno-omit-frame-pointer... yes
checking whether clang++ supports -glldb... yes
checking whether clang++ supports -fstandalone-debug... yes
checking whether clang++ supports -Wl,--no-as-needed... yes
checking whether clang++ supports -Wl,--as-needed... yes
checking for swapcontext... yes
checking if shared libs need -fPIC... yes
checking for dlopen with CFLAGS="" LIBS=""... yes
checking if --export-dynamic linker option is supported/needed... both
checking for flags needed to link with static libs containing simple modules... --whole-archive
configure: NOTE: Use the following syntax when linking with static libraries
configure: containing simple modules and other dynamically registered components:
configure:    clang++ ... -Wl,--whole-archive <libs> -Wl,--no-whole-archive ...
checking whether linker supports -rpath... yes
checking for bison... bison -y
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for make... make
checking for perl... perl
checking for swig... swig
checking for python3... python3
checking if all necessary Python modules are available... yes
checking for math with CFLAGS=" -fPIC" LIBS=""... yes
checking for standard C++ lib with CFLAGS=" -fPIC" LIBS="-lstdc++"... yes
checking for dlopen with CFLAGS=" -fPIC" LIBS=""... yes
checking for qmake-qt5... no
checking for qmake5... no
checking for qmake... /usr/bin/qmake
checking for moc-qt5... no
checking for moc5... no
checking for moc... /usr/lib64/qt5/bin/moc
checking for uic-qt5... no
checking for uic5... no
checking for uic... /usr/lib64/qt5/bin/uic
checking for rcc-qt5... no
checking for rcc5... no
checking for rcc... /usr/lib64/qt5/bin/rcc
checking for Qt5 with CFLAGS="  -fPIC -isystem /usr/include/qt5  -fPIC -isystem /usr/include/qt5" LIBS="-lQt5Gui -lQt5Core -lQt5Widgets -lQt5PrintSupport -lQt5OpenGL -L/usr/lib64"... yes
checking for OpenSceneGraph with CFLAGS=" -fPIC  -Wno-deprecated-register -Wno-unused-function -fno-omit-frame-pointer  " LIBS=" -Wl,--export-dynamic  -losg -losgDB -losgGA -losgViewer -losgUtil -lOpenThreads"... yes
checking for clang++ option to support OpenMP... -fopenmp
checking for PTHREAD with CFLAGS=" -fPIC " LIBS="-lpthread"... yes
configure: creating ./config.status
config.status: creating Makefile.inc
config.status: creating src/qtenv/qtenv.pri

Configuration phase finished. Use 'make' to build OMNeT++.
```

System is Gentoo Linux, with Python 3.9 and 3.10, OpenRC, glibc-2.34, clang-14.0.0.

**Comment by rhornig** [comment]
Strange. Clang seems to be quite new here. Could you possibly force in `configure.user` to use GCC for building? If this is `clang` specific, I need to upgrade my system to be able to reprodcuce this.

**Comment by SpeedJack** [comment]
I've tried setting `PREFER_CLANG=no` in `configure.user` and got the same error:
```
MSGC: sim_std.msg
/home/speedjack/repos/omnetpp-6.0/bin/opp_msgtool: symbol lookup error: /home/speedjack/repos/omnetpp-6.0/bin/opp_msgtool: undefined symbol: _ZN7omnetpp6nedxml11MsgCompiler19BUILTIN_DEFINITIONSE
make[2]: *** [Makefile:160: sim_std_m.cc] Error 127
make[1]: *** [Makefile:134: sim] Error 2
make: *** [Makefile:35: allmodes] Error 2
```
Then I've also tried with `PREFER_LLD=no` but I still have the same error.

Here my actual `configure.user`:
```
PREFER_CLANG=no
PREFER_LLD=no
WITH_QTENV=yes
WITH_OSG=yes
WITH_OSGEARTH=no
WITH_NETBUILDER=yes
WITH_LIBXML=no
WITH_PARSIM=no
PREFER_SQLITE_RESULT_FILES=no
WITH_SYSTEMC=no
SHARED_LIBS=yes
WITH_AKAROA=no
```

GCC version 11.2.1

**Comment by SpeedJack** [comment]
I've tried downgrading gcc to version 9.4.0 but the issue is still here.

**Comment by SpeedJack** [comment]
Ok, I've solved the issue.

With `strace` on `opp_msgtool` I've found that the dynamic loader was trying to load libraries from the library path of the old version of omnet (5.7). This was due to my system configuration: I've set `LD_LIBRARY_PATH=${HOME}/repos/omnetpp-5.7/lib` in my `.bashrc`. Removing this line from `.bashrc` has solved the issue.

Anyway, I think that this should not happen: as far as I know, the dynamic loader should be able to determine that the version of the library found is not compatible and should continue searching for a compatible library in the list of directories to search.

**Comment by rhornig** [comment]
Hmm. Thanks for tracking this down. I'm not sure the dynamic loader does anything to ensure compatibility. It only looks for a specific file names and tries to load the first with a patching filename. Of course if the omnet library names would contain also a version numbers, this would not be a problem. We try to avoid the requirement to set **anything** globally for omnet. So you always have to run `source setenv`, but on the other hand you would not get such a surprises.

BTW, setting LD_LIBRARY_PATH is not required for omnet since omnet 5.0 as we are providing the proper `rpath` on the linker command line, so a simulation will always find its proper library version without any manual assistance (unless you move around your omnet installation to a different path after compiling it). I suggest to get rid all omnet related stuff from your `.bashrc`. If you want to have an omnet installation available by default, use this in your `.profile`

    [ -f "$HOME/omnetpp-dev/setenv" ] && source "$HOME/omnetpp-dev/setenv" -f

**Comment by aimanakkad** [comment]
Hello Rudolf!
I am working with INET framework 4.4.1 with omnet++ 6.0.1 under Ubuntu 20.04.5 LTS focal.
Unfortunately, I am not able to run the videostreaming showcase emulation until now, although
I spent a few weeks trying to solve the errors which I get.
Could you please recommend me what to do in getting this issue resolved?
I will be highly grateful to you.
Kindest regards,
Aiman
P.S.: The error I get is as follows:
ld.lld: error: duplicate symbol: swresample_configuration
>>> defined at swresample.c:42 (libswresample/swresample.c:42)
>>>            swresample.o:(swresample_configuration) in archive /usr/local/lib/libswresample.a
>>> defined at swresample.c:42 (libswresample/swresample.c:42)
>>>            swresample.o:(.text+0x120) in archive /usr/local/lib/libswresample.a
 
ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
make[1]: Leaving directory '/home/aiman/omnetpp-6.0.1/samples/inet/src'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:1848: ../out/clang-release/src/libINET.so] Error 1
make: *** [Makefile:7: all] Error 2
"make MODE=release -j16 all" terminated with exit code 2. Build might be incomplete.
