### ISSUE TITLE
INET framework 4.4.1

### ISSUE THREAD

**Issue by aimanakkad** [omnetpp/omnetpp#945]
Hello Rudolf!
I am working with INET framework 4.4.1 with omnet++ 6.0.1 under Ubuntu 20.04.5 LTS focal.
Unfortunately, I am not able to run the videostreaming showcase emulation until now, although
I spent a few weeks trying to solve the errors which I get.
Could you please recommend me what to do in getting this issue resolved?
I will be highly grateful to you.
Kindest regards,
Aiman
P.S.: The error I get is as follows:
ld.lld: error: duplicate symbol: swresample_configuration

            defined at swresample.c:42 (libswresample/swresample.c:42)
            swresample.o:(swresample_configuration) in archive /usr/local/lib/libswresample.a
            defined at swresample.c:42 (libswresample/swresample.c:42)
            swresample.o:(.text+0x120) in archive /usr/local/lib/libswresample.a

ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
make[1]: Leaving directory '/home/aiman/omnetpp-6.0.1/samples/inet/src'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:1848: ../out/clang-release/src/libINET.so] Error 1
make: *** [Makefile:7: all] Error 2
"make MODE=release -j16 all" terminated with exit code 2. Build might be incomplete.

**Comment by aimanakkad** [comment]
I am getting now another error when running the videostreaming omnetpp.ini
Preparing for running configuration General, run #0...

<!> Error: Cannot create event scheduler: class "inet::RealTimeScheduler" not found

**Comment by aimanakkad** [comment]
OMNeT++ Discrete Event Simulation  (C) 1992-2022 Andras Varga, OpenSim Ltd.
Version: 6.0.1, build: 220831-e4f07d04b8, edition: Academic Public License -- NOT FOR COMMERCIAL USE
See the license for distribution terms and warranty disclaimer

Setting up Cmdenv...

Starting...

$ cd /home/aiman/omnetpp-6.0.1/samples/inet/showcases/emulation/videostreaming
$ opp_run -r 0 -m -u Cmdenv -n ../../../examples:../..:../../../src:../../../tests/validation:../../../tests/networks:../../../tutorials -x inet.common.selfdoc;inet.linklayer.configurator.gatescheduling.z3;inet.showcases.visualizer.osg;inet.transportlayer.tcp_lwip;inet.visualizer.osg;inet.examples.voipstream --image-path=../../../images omnetpp.ini

Loading NED files from ../../../examples:  180
Loading NED files from ../..:  72
Loading NED files from ../../../src:  1134
Loading NED files from ../../../tests/validation:  5
Loading NED files from ../../../tests/networks:  6
Loading NED files from ../../../tutorials:  20

Preparing for running configuration General, run #0...

<!> Error: Cannot create event scheduler: class "inet::RealTimeScheduler" not found

End.

Simulation terminated with exit code: 1
Working directory: /home/aiman/omnetpp-6.0.1/samples/inet/showcases/emulation/videostreaming
Command line: opp_run -r 0 -m -u Cmdenv -n ../../../examples:../..:../../../src:../../../tests/validation:../../../tests/networks:../../../tutorials -x inet.common.selfdoc;inet.linklayer.configurator.gatescheduling.z3;inet.showcases.visualizer.osg;inet.transportlayer.tcp_lwip;inet.visualizer.osg;inet.examples.voipstream --image-path=../../../images omnetpp.ini

Environment variables:
PATH=/home/aiman/omnetpp-6.0.1/bin::/home/aiman/omnetpp-6.0.1/bin:/home/aiman/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH=/home/aiman/omnetpp-6.0.1/lib::
OMNETPP_RELEASE=omnetpp-6.0.1
OMNETPP_IMAGE_PATH=/home/aiman/omnetpp-6.0.1/images
